### ISSUE TITLE
Need preload feature like preload_page_view package

### ISSUE THREAD

**Issue by moinkhan780** [okaryo/lazy_load_indexed_stack#5]
Where next index is automatically preload. so for this we dont have to wait for for widget to load

https://pub.dev/packages/preload_page_view

**Comment by okaryo** [comment]
@moinkhan780 
Sorry for the late reply.

Thank you for the issue! That's a good idea.
While PageView benefits from preloading because it displays adjacent pages in sequence, implementing the same for IndexedStack might need some tweaks since you can access any page at any time.
To better address this, I have a few clarifications:

* In what situations did you feel the need for preloading in IndexedStack?
* What kind of API would make sense for implementing preload in IndexedStack?

**Comment by moinkhan780** [comment]
For example consider QUIZ where we have multiple questions from the api

**Comment by okaryo** [comment]
done in #6
